### PR TITLE
Add zh-rTW translations.

### PR DESCRIPTION
**Pull request by s8321414**
I added zh-rTW translations, please review and merge it :smiley:

### CODE REVIEW

**Comment by srowen** [comment]
Pardon my ignorance, but is this a simple or traditional Chinese translation? is it not already covered by zh or zh-rCN?

I can't update the Android app any further, so there's no point in updating the app from here anyway.

**Comment by s8321414** [comment]
@srowen This is Traditional Chinese (Taiwan) and not covered by zh and zh-rCN, in fact, zh can't show on a zh-rTW Android system...

**Comment by srowen** [comment]
Hm, OK, so there are supposed to be 3 variants? I can merge it but it can't be released.

**Comment by srowen** [comment]
If you are reacting to 'can't be released' -- the app can't be published to the app store anymore, so I don't know if it matters what we update here.

I thought `zh` was already a traditional Chinese translation, but of course I have no knowledge of the language myself. Why wouldn't a `zh-rTW` device match it? if the translation is the same, we can symlink if needed.

**Comment by s8321414** [comment]
I have no idea why, but I can see some terms in zh are different from zh-rTW.

**Comment by Yairimedinac4621** [comment]
Thank you

**Pull request closed without merging**
