### PR TITLE
Make MultiFinderPatternFinder a public class

### PR DESCRIPTION
**Pull request by yerar**
As comented before in #1312 , MultiFinderPatternFinder can be a public class like its parent.

### CODE REVIEW

**Comment by srowen** [comment]
I'm not against it, but what's your use case? It's a bit of an implementation detail, so that's why it wasn't public.
You would need to make more than the class public to use it, I think.

**Comment by yerar** [comment]
> I'm not against it, but what's your use case? It's a bit of an implementation detail, so that's why it wasn't public.
> You would need to make more than the class public to use it, I think.

I'm working on a project with some QR detection problems to be solved. I only need to know where are the Finder Patterns in the image, but I don't need all the additional information as the version, the alignment patterns or the decoded data. Once I have the Finders info, I apply custom transformations (such as cylindrical) to the QR.

So, for performance reasons, using MultiFinderPatternFinder is the way to go, instead of MultiDetector or QRCodeMultiReader that compute additional information not needed.

**Review by srowen — COMMENTED** [review]
OK, I think you'll need the constructor on line 89 to be public too.

**Comment by yerar** [comment]
Done!

**Pull request merged**
