### PR TITLE
Farsi Language

### PR DESCRIPTION
**Pull request by PedPak**
add ability to support Farsi (Persian) Language in app.

### CODE REVIEW

**Comment by srowen** [comment]
Oh interesting, does Android support it as a Locale too? I didn't find an official reference but it looks like it.

**Comment by c2c2** [comment]
Hi,
iso code is Fa-IR and support from android 5. add to translate

**Comment by Carringguns** [comment]
_first messages ive got _ever__

**idk but ive been at this for hrs**

**Comment by srowen** [comment]
Thanks @PedPak I merged this at last after a rebase.

**Pull request closed without merging**
