### PR TITLE
Added camera flip functionality.

### PR DESCRIPTION
**Pull request by JacobVanAssche**
User can now swap between Front and Rear facing camera on the screen. Preference will be saved.

### CODE REVIEW

**Comment by srowen** [comment]
I think the problem is that this ignores the existing control over the camera selection, including dealing with real cases like not having a front camera. I would not be able to merge this.

**Comment by Marylatha** [comment]
Porn sex hard core

**Comment by Marylatha** [comment]
Undressed  sex

**Comment by Marylatha** [comment]
Sex

**Pull request closed without merging**
