### PR TITLE
Support Adaptive Icons & Fixed strings.xml Korean

### PR DESCRIPTION
**Pull request by kdwoo1217**
#996 I think he want to like this called Adaptive Icons on Android Oreo.
And I Fixed strings.xml Korean because some sentences are too stiff to Korean.
I don't know this is right PR.
I read your Release Process in here [https://github.com/zxing/zxing/wiki/Getting-Started-Developing](url).
But I don't know what it means....
If this PR is wrong the send me E-Mail or comment here. Thank you.

screenshot_20180614-005911
screenshot_20180614-005928
screenshot_20180614-010001

### CODE REVIEW

**Comment by srowen** [comment]
This has a number of superfluous XML changes that need to be reverted. Also please separate out the Korean strings change. Finally, do you really need new copies of the icon? can the adaptive icon not just mask the existing icon somehow? maybe not

**Comment by kdwoo1217** [comment]
I just fixed AndroidManifest.xml in zxing/anroid/AndroidManifest.xml and Add ic_launcher files in zxing/android/res/mipmap folders.
Adaptive Icon is If I want change to possible icon background using launcher settings like that.
That is separate icon foreground and background.

**Comment by kdwoo1217** [comment]
And how to separate Korean strings change? 
I do not know because I am a student who has just used Git.

**Comment by srowen** [comment]
I think you'll want to start over and delete this pull request and branch. Make a branch with just the Korean strings change, push it, and open a PR for that branch. Make another branch with the icon change only, push it, make a PR for that branch. Before pushing, ensure you do not commit any other changes to other files. You can see here than about 70 XML files had their "UTF-8" declaration changed.

**Pull request closed without merging**
