### PR TITLE
Update Basque translation

### PR DESCRIPTION
**Pull request by aldatsa**
I'm the original Basque translator of Barcode Scanner for Android. I've updated the translation.

### CODE REVIEW

**Comment by srowen** [comment]
Thank you!

**Comment by aldatsa** [comment]
Sorry @srowen, I don't understand. Should I do something?

**Comment by srowen** [comment]
No, just went back and tagged a bunch of issues with labels and milestones.

**Comment by aldatsa** [comment]
OK!

**Pull request merged**
