### PR TITLE
Minimal encoding for Data Matrix with multi ECI and GS1-FNC1 support (2nd)

### PR DESCRIPTION
**Pull request by AlexGeller1**
Feature is off by default and can be activated by EncodeTypeHint.DATA_MATRIX_COMPACT

### CODE REVIEW

**Review by srowen — COMMENTED** [review]
Looks OK if tests pass. If there are minor tweaks to style I'd recommend I can sort them out later.

**Comment by AlexGeller1** [comment]
There are three @Seans in the code where I had doubts and wanted your opinion. There are two in HighLevelEncodeTestCase and one in DataMatrixWriter. That one is important since I need to know how users encode FNC1 in input strings. I implemented it by the GS (ASCII 29) character but perhaps it is done differently by some other escape mechanism in ZXing.

**Comment by AlexGeller1** [comment]
One other thing, MACRO5 and MACRO6 isn't implemented yet. It strips the '[)>' stuff but doesn't insert the values. That needs to be done still.

**Comment by srowen** [comment]
I don't know the details of that enough to comment - have forgotten or never knew it. I'd say in general, leave existing behavior unless sure it should be something different; implement functionality that is coherent in itself even if some parts could be extended, rather than leave something partly implemented but not quite working. Up to your judgment from there.

**Comment by AlexGeller1** [comment]
I looked at the source Code128Writer. Apparently it uses the character 0xf1 to encode FNC1 in input. What I have implemented is more what is in place for QR-Code (there the AI it is the GS character because GS1 says to use it instead of FNC1). For any bat code GS says that the decoder needs to yield GS for FNC1 on decoding so that using it for encoding makes sense in my eyes. The code-128 0xf1 seems odd to me but perhaps it was used because code-128 additionally has FNC2, FNC3 and FNC4 which are encoded by 0xf2 through 0xf4.

**Comment by AlexGeller1** [comment]
> Looks OK if tests pass. If there are minor tweaks to style I'd recommend I can sort them out later.

Yes, all test pass.

**Review by srowen — APPROVED** [review]

**Pull request merged**
