### PR TITLE
Ignore additional PDF417 barcode rows, https://github.com/zxing/zxing/issues/449

### PR DESCRIPTION
**Pull request by graug**
Some barcode generators (e.g. Okapi) seem to generate additional barcode
rows at the end of the barcode, which can be decoded as valid barcode
rows, but actually contain garbage. The barcode metadata states that
these additional rows are not part of the barcode. So we ignore those
addional rows when parsing the barcode. This could potentially also
happen (though quite unlikely) if data after the barcode looks like a
barcode row.

### CODE REVIEW

**Comment by srowen** [comment]
Interesting, if it doesn't break detection of any existing barcodes, and doesn't introduce significantly false positives (highly unlikely) then this could be a good change. Right now it's failing the CI build because of a style problem -- tabs in one of the lines? https://travis-ci.org/zxing/zxing/jobs/78208877

**Comment by graug** [comment]
Sorry about the formatting botch. I removed the tabs.

**Comment by srowen** [comment]
OK, seems reasonable to me, thank you. I'm going to merge.

**Comment by graug** [comment]
thx for the review and merging it.

**Pull request merged**
