### PR TITLE
dependency-info.html: sbt should use %

### PR DESCRIPTION
**Pull request by nafg**
%% is for libraries cross-built against different scala versions.

### CODE REVIEW

**Comment by srowen** [comment]
This is auto generated by the maven site plugin. It would be best to propose changes to this output in the plugin project.

**Comment by nafg** [comment]
Can you give me a more targeted pointer?

**Comment by srowen** [comment]
This is the site plugin: http://maven.apache.org/plugins/maven-site-plugin/
Does the formulation not work at all? or just suboptimal for projects that don't publish Scala-specific "_2.10" artifacts?
I assume it would be simple to just expand the boilerplate text it generates to cover this case.

**Comment by nafg** [comment]
Apparently I'm not the first to notice: http://jira.codehaus.org/browse/MPIR-296
Seems it's fixed for maven-project-info-reports-plugin 2.8 which seems to not be out yet.

Thanks!

**Pull request closed without merging**
