### PR TITLE
Improved slovene translation for Android

### PR DESCRIPTION
**Pull request by codewell4**

### CODE REVIEW

**Comment by ocdtrekkie** [comment]
You should probably try only sending the translation commit in the PR, since the CODE_93 writer commit has already been rejected by the maintainer. ;)

**Comment by codewell4** [comment]
You're right. Today was my first pull request so I'm still catching up...

**Comment by srowen** [comment]
Yes please, just revert the last commit, squash and force-push, or just open a new PR with the translation commit

**Comment by ocdtrekkie** [comment]
I'm bad at git too. ;) Strong advice is to create separate branches off of the master for each separate thing you're working on. Makes it much easier to make clean pull requests.

**Comment by codewell4** [comment]
Sorry I guess I'll close this pull request. I have to read GitHub instructions how to revert it.
I'll take your advice on making a separate branch, that seems logical.

**Comment by srowen** [comment]
Yeah sometimes it's easier just to restart. Just make a new branch from master, commit, open a new PR from it.

**Comment by codewell4** [comment]
Sorry this will take a while. I'll try it again with a new branch. Probably not today :|

**Pull request closed without merging**
