### PR TITLE
Added the "Get Started Developing" link in the README.md

### PR DESCRIPTION
**Pull request by az-ericso**
It is really hard to find the instruction.

### CODE REVIEW

**Comment by srowen** [comment]
Yes the new layout no longer links wikis on the front page. I am fine with this but I think it should reference getting started _developing_

**Comment by az-ericso** [comment]
I already did.  Is that the wrong link?

**Comment by srowen** [comment]
The text you added just talks about 'getting started' but this has only to do with development

**Comment by az-ericso** [comment]
how about now?

**Pull request merged**
