### PR TITLE
Added rawBytes functionality to the Aztec scanner

### PR DESCRIPTION
**Pull request by iSDP**
Added rawBytes functionality to the Aztec scanner

### CODE REVIEW

**Comment by srowen** [comment]
This reformats a bunch of code with different spacing, or tabs instead of spaces. I can't make out the intended change. Can you reopen with just the code change and no whitespace changes?

**Comment by iSDP** [comment]
That's done automatically by Android Studio, sadly.

**Comment by johanhar** [comment]
Was this ever reopened and accepted?

**Comment by oelna** [comment]
I hope this gets resolved eventually.

**Comment by iSDP** [comment]
Me too, didn't have the time to go back and turn tabs back into spaces :(

I actually wanted to do this today, until I woke up and saw this! 

Thank you very much for your effort!

**Pull request closed without merging**
